apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-certificate
spec:
  dnsNames:
    - back.apps.ci-ln-qpmgk7k-76ef8.aws-2.ci.openshift.org
  issuerRef:
    name: letsencrypt
  secretName: janus-idp-cert
