apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: "backstage"
  labels: 
    app.kubernetes.io/component: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backstage
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backstage
      annotations:
        checksum/app-config: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    spec:
      serviceAccountName: default
      containers:
        - resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
          name: backstage-showcase
          image: quay.io/rh_ee_pknight/backstage-showcase:key
          imagePullPolicy: "Always"
          command:
            - node
            - packages/backend
          env:
            - name: APP_CONFIG_app_baseUrl
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_app_baseUrl
                  name: values-app-config
            - name: APP_CONFIG_backend_baseUrl
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_backend_baseUrl
                  name: values-app-config
            - name: APP_CONFIG_backend_cors_origin
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_backend_cors_origin
                  name: values-app-config
            - name: APP_CONFIG_auth_environment
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_auth_environment
                  name: values-app-config
            - name: APP_CONFIG_catalog_providers_keycloakOrg_default_baseUrl
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_catalog_providers_keycloakOrg_default_baseUrl
                  name: values-app-config
            - name: APP_CONFIG_catalog_providers_keycloakOrg_default_loginRealm
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_catalog_providers_keycloakOrg_default_loginRealm
                  name: values-app-config
            - name: APP_CONFIG_catalog_providers_keycloakOrg_default_realm
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_catalog_providers_keycloakOrg_default_realm
                  name: values-app-config
            - name: APP_CONFIG_catalog_providers_keycloakOrg_default_clientId
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_catalog_providers_keycloakOrg_default_clientId
                  name: values-app-config
            - name: APP_CONFIG_catalog_providers_keycloakOrg_default_clientSecret
              valueFrom:
                secretKeyRef:
                  key: APP_CONFIG_catalog_providers_keycloakOrg_default_clientSecret
                  name: values-app-config
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                secretKeyRef:
                  key: NODE_TLS_REJECT_UNAUTHORIZED
                  name: values-app-config
          ports:
            - name: backend
              containerPort: 7007
              protocol: TCP
        - resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
          args:
          - --provider=oidc
          - --email-domain=*
          - --upstream=http://localhost:7007
          - --http-address=0.0.0.0:4180
          - --skip-provider-button
          env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: OAUTH2_PROXY_CLIENT_ID
                name: oauth2-values
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: OAUTH2_PROXY_CLIENT_SECRET
                name: oauth2-values
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                key: OAUTH2_PROXY_COOKIE_SECRET
                name: oauth2-values
          - name: OAUTH2_PROXY_OIDC_ISSUER_URL
            valueFrom:
              secretKeyRef:
                key: OAUTH2_PROXY_OIDC_ISSUER_URL
                name: oauth2-values
          - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
            valueFrom:
              secretKeyRef:
                key: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
                name: oauth2-values
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: IfNotPresent
          name: oauth2-proxy
          ports:
          - containerPort: 4180
            name: oauth2-proxy
            protocol: TCP