apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  namespace: "janus-idp"
  labels:
    app.kubernetes.io/component: backstage
  annotations:
    backstage.io/kubernetes-id: janus-idp
spec:
  tls:
    - hosts:
      - back.apps.ci-ln-qpmgk7k-76ef8.aws-2.ci.openshift.org
      secretName: janus-idp-cert
  rules:
    - host: back.apps.ci-ln-gz6n712-76ef8.aws-2.ci.openshift.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage
                port:
                  number: 7007
