apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - issuer.yaml
  - certificate.yaml
  - keycloak
commonLabels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/part-of: backstage
# labels:
#   - pairs:
#       app.kubernetes.io/name: backstage
#       app.kubernetes.io/instance: backstage
#     includeSelectors: false
patchesJson6902:
  - patch: |-
      - op: remove
        path: /spec/selector/app.kubernetes.io~1name
      - op: remove
        path: /spec/selector/app.kubernetes.io~1instance
      - op: remove
        path: /spec/selector/app.kubernetes.io~1part-of
    target:
      kind: Service
      version: v1
      name: keycloak
