apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - issuer.yaml
  - certificate.yaml
  - keycloak
commonLabels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
# labels:
#   - pairs:
#       app.kubernetes.io/name: backstage
#       app.kubernetes.io/instance: backstage
#     includeSelectors: false
