apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - keycloak
commonLabels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
    backstage.io/kubernetes-id: backstage
    app.kubernetes.io/part-of: backstage