apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources: 
  - deployment.yaml
  - ingress.yaml
  - service.yaml
commonLabels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage