apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - issuer.yaml
  - certificate.yaml
  - keycloak
commonLabels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: backstage
patches:
  - patch: |-
      - op: remove
        path: /spec/selector/
    target:
      version: v1
      kind: service
      name: keycloak