apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources:
  - certificate.yaml
  - deploymentconfig.yaml
  - imagestream.yaml
  - ingress.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
labels:
  - pairs:
      application: sonarqube
    includeSelectors: false
