apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ssl-certificate
spec:
  dnsNames:
    - key.apps.ci-ln-qwvtmmk-76ef8.aws-2.ci.openshift.org
  issuerRef:
    name: letsencrypt
  secretName: keycloak-cert
