apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ssl-certificate
spec:
  dnsNames:
    - key.apps-crc.testing
  issuerRef:
    name: letsencrypt
  secretName: keycloak-cert
