apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
labels:
  app.kubernetes.io/part-of: backstage
spec:
  tls:
    - hosts: 
      - key.apps.ci-ln-h8l4rcb-76ef8.origin-ci-int-aws.dev.rhcloud.com
      secretName: keycloak-cert
  rules:
    - host: key.apps.ci-ln-h8l4rcb-76ef8.origin-ci-int-aws.dev.rhcloud.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
