apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
spec:
  tls:
    - hosts: 
      - keycloak-janus-idp.apps-crc.testing
      secretName: janus-idp-cert2
  rules:
    - host: keycloak-janus-idp.apps-crc.testing
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: keycloak
                port:
                  number: 8080