apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - deploymentconfig.yaml
  - ingress.yaml
  - service.yaml
  - certificate.yaml
labels:
  - pairs:
      application: keycloak
    includeSelectors: false
# patchesJson6902:
#   - patch: |-
#       - op: remove
#         path: /spec/selector/app.kubernetes.io~1name
#       - op: remove
#         path: /spec/selector/app.kubernetes.io~1instance
#     target:
#       kind: Service
#       version: v1
#       name: keycloak