apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - deploymentconfig.yaml
  - ingress.yaml
  - service.yaml
  - certificate.yaml
labels:
  - pairs:
      application: keycloak
    includeSelectors: false
# commonLabels:
#   application: keycloak
patchesJson6902:
  - patch: |-
      - op: add
        path: /spec/selector/test
        value: Pat
    target:
      kind: Service
      version: v1
      name: keycloak