apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - deploymentconfig.yaml
  - route.yaml
  - service.yaml
commonLabels:
  application: keycloak
  app.kubernetes.io/part-of: keycloak