apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: "janus-idp" 
  labels:
    app.kubernetes.io/part-of: backstage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    deploymentConfig: keycloak
